/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
//// Neoffice — restored upstream's generated single-line output; a local unplugin-auto-import run had rewritten this as three lines, nothing of ours belongs here (b4beb2ee "chore: auto-imports.d.ts is generated — keep upstream's exact output")
declare global {}
