#!/usr/bin/env python3
"""
Comprehensive French translation for CRM PO file.
Handles all 966 untranslated strings.
"""

import re
import sys

# Comprehensive translation dictionary
TRANSLATIONS = {
    # Actions - verbs
    'Add': 'Ajouter',
    'Add a comment': 'Ajouter un commentaire',
    'Add a note': 'Ajouter une note',
    'Add Comment': 'Ajouter un commentaire',
    'Add contact': 'Ajouter un contact',
    'Add Deal': 'Ajouter une affaire',
    'Add email': 'Ajouter un email',
    'Add Filter': 'Ajouter un filtre',
    'Add Lead': 'Ajouter un prospect',
    'Add mobile no': 'Ajouter un numéro de mobile',
    'Add New': 'Ajouter nouveau',
    'Add Note': 'Ajouter une note',
    'Add Organization': 'Ajouter une organisation',
    'Add phone': 'Ajouter un téléphone',
    'Add Task': 'Ajouter une tâche',
    'Add to list': 'Ajouter à la liste',
    'Add website': 'Ajouter un site web',
    'Added by': 'Ajouté par',
    'Added on': 'Ajouté le',
    'All': 'Tout',
    'All Activity': 'Toute l\'activité',
    'All Contacts': 'Tous les contacts',
    'All Deals': 'Toutes les affaires',
    'All Leads': 'Tous les prospects',
    'All Organizations': 'Toutes les organisations',
    'All Tasks': 'Toutes les tâches',
    'Apply': 'Appliquer',
    'Apply Filters': 'Appliquer les filtres',
    'Archive': 'Archiver',
    'Archived': 'Archivé',
    'Are you sure?': 'Êtes-vous sûr ?',
    'Assign': 'Assigner',
    'Assign To': 'Assigner à',
    'Assigned': 'Assigné',
    'Assigned To': 'Assigné à',
    'Assigned to': 'Assigné à',
    'Back': 'Retour',
    'Call': 'Appel',
    'Call Duration': 'Durée de l\'appel',
    'Call Log': 'Journal d\'appel',
    'Call Logs': 'Journaux d\'appel',
    'Call Status': 'Statut de l\'appel',
    'Cancel': 'Annuler',
    'Change': 'Modifier',
    'Clear': 'Effacer',
    'Clear All': 'Tout effacer',
    'Clear Filters': 'Effacer les filtres',
    'Click to select': 'Cliquer pour sélectionner',
    'Close': 'Fermer',
    'Closed': 'Fermé',
    'Comment': 'Commentaire',
    'Comments': 'Commentaires',
    'Company': 'Société',
    'Complete': 'Terminer',
    'Completed': 'Terminé',
    'Confirm': 'Confirmer',
    'Contact': 'Contact',
    'Contacts': 'Contacts',
    'Continue': 'Continuer',
    'Convert': 'Convertir',
    'Convert to Deal': 'Convertir en affaire',
    'Converted': 'Converti',
    'Copy': 'Copier',
    'Create': 'Créer',
    'Create Call Log': 'Créer un journal d\'appel',
    'Create Contact': 'Créer un contact',
    'Create Deal': 'Créer une affaire',
    'Create Lead': 'Créer un prospect',
    'Create Note': 'Créer une note',
    'Create Organization': 'Créer une organisation',
    'Create Task': 'Créer une tâche',
    'Created': 'Créé',
    'Created By': 'Créé par',
    'Created On': 'Créé le',
    'Creation': 'Création',
    'Custom': 'Personnalisé',
    'Customer': 'Client',
    'Dashboard': 'Tableau de bord',
    'Date': 'Date',
    'Deal': 'Affaire',
    'Deal Value': 'Valeur de l\'affaire',
    'Deals': 'Affaires',
    'Default': 'Par défaut',
    'Delete': 'Supprimer',
    'Deleted': 'Supprimé',
    'Description': 'Description',
    'Details': 'Détails',
    'Discard': 'Abandonner',
    'Done': 'Terminé',
    'Download': 'Télécharger',
    'Draft': 'Brouillon',
    'Due': 'Échéance',
    'Due Date': 'Date d\'échéance',
    'Edit': 'Modifier',
    'Email': 'Email',
    'Email Address': 'Adresse email',
    'Emails': 'Emails',
    'Empty': 'Vide',
    'End Date': 'Date de fin',
    'Enter': 'Entrer',
    'Error': 'Erreur',
    'Expected Closing': 'Clôture prévue',
    'Export': 'Exporter',
    'Field': 'Champ',
    'Fields': 'Champs',
    'File': 'Fichier',
    'Files': 'Fichiers',
    'Filter': 'Filtrer',
    'Filter by': 'Filtrer par',
    'Filters': 'Filtres',
    'First Name': 'Prénom',
    'Follow Up': 'Suivi',
    'Follow up': 'Suivi',
    'Full Name': 'Nom complet',
    'General': 'Général',
    'Group': 'Groupe',
    'Group By': 'Grouper par',
    'Help': 'Aide',
    'Hide': 'Masquer',
    'History': 'Historique',
    'Home': 'Accueil',
    'Import': 'Importer',
    'In Progress': 'En cours',
    'Incoming': 'Entrant',
    'Industry': 'Industrie',
    'Info': 'Information',
    'Information': 'Information',
    'Invalid': 'Invalide',
    'Is Active': 'Est actif',
    'Language': 'Langue',
    'Last Modified': 'Dernière modification',
    'Last Modified By': 'Modifié par',
    'Last Name': 'Nom de famille',
    'Lead': 'Prospect',
    'Lead Owner': 'Propriétaire du prospect',
    'Lead Source': 'Source du prospect',
    'Lead Status': 'Statut du prospect',
    'Leads': 'Prospects',
    'Link': 'Lien',
    'List': 'Liste',
    'Loading': 'Chargement',
    'Loading...': 'Chargement...',
    'Location': 'Emplacement',
    'Log': 'Journal',
    'Lost': 'Perdu',
    'Lost Reason': 'Raison de la perte',
    'Manager': 'Responsable',
    'Mark as': 'Marquer comme',
    'Mark as Lost': 'Marquer comme perdu',
    'Mark as Won': 'Marquer comme gagné',
    'Meeting': 'Réunion',
    'Message': 'Message',
    'Mobile': 'Mobile',
    'Mobile No': 'N° de mobile',
    'Modified': 'Modifié',
    'Modified By': 'Modifié par',
    'Modified On': 'Modifié le',
    'More': 'Plus',
    'Name': 'Nom',
    'New': 'Nouveau',
    'New Call Log': 'Nouveau journal d\'appel',
    'New Contact': 'Nouveau contact',
    'New Deal': 'Nouvelle affaire',
    'New Lead': 'Nouveau prospect',
    'New Note': 'Nouvelle note',
    'New Organization': 'Nouvelle organisation',
    'New Task': 'Nouvelle tâche',
    'Next': 'Suivant',
    'No': 'Non',
    'No data': 'Aucune donnée',
    'No records found': 'Aucun enregistrement trouvé',
    'No results found': 'Aucun résultat trouvé',
    'None': 'Aucun',
    'Not Set': 'Non défini',
    'Note': 'Note',
    'Notes': 'Notes',
    'Notification': 'Notification',
    'Notifications': 'Notifications',
    'OK': 'OK',
    'Open': 'Ouvrir',
    'Opened': 'Ouvert',
    'Options': 'Options',
    'Order By': 'Trier par',
    'Organization': 'Organisation',
    'Organization Name': 'Nom de l\'organisation',
    'Organizations': 'Organisations',
    'Other': 'Autre',
    'Outgoing': 'Sortant',
    'Owner': 'Propriétaire',
    'Pending': 'En attente',
    'Phone': 'Téléphone',
    'Phone No': 'N° de téléphone',
    'Pipeline': 'Pipeline',
    'Pipelines': 'Pipelines',
    'Please select': 'Veuillez sélectionner',
    'Preview': 'Aperçu',
    'Previous': 'Précédent',
    'Priority': 'Priorité',
    'Profile': 'Profil',
    'Qualified': 'Qualifié',
    'Quick Add': 'Ajout rapide',
    'Reassign': 'Réassigner',
    'Recent': 'Récent',
    'Record': 'Enregistrement',
    'Records': 'Enregistrements',
    'Refresh': 'Actualiser',
    'Reload': 'Recharger',
    'Remove': 'Retirer',
    'Rename': 'Renommer',
    'Reopen': 'Rouvrir',
    'Report': 'Rapport',
    'Reports': 'Rapports',
    'Required': 'Obligatoire',
    'Reset': 'Réinitialiser',
    'Restore': 'Restaurer',
    'Result': 'Résultat',
    'Results': 'Résultats',
    'Revenue': 'Revenu',
    'Role': 'Rôle',
    'Roles': 'Rôles',
    'Save': 'Enregistrer',
    'Save Changes': 'Enregistrer les modifications',
    'Saved': 'Enregistré',
    'Search': 'Rechercher',
    'Search...': 'Rechercher...',
    'Select': 'Sélectionner',
    'Select All': 'Tout sélectionner',
    'Select Date': 'Sélectionner une date',
    'Select User': 'Sélectionner un utilisateur',
    'Selected': 'Sélectionné',
    'Send': 'Envoyer',
    'Settings': 'Paramètres',
    'Share': 'Partager',
    'Show': 'Afficher',
    'Show All': 'Tout afficher',
    'Show More': 'Afficher plus',
    'Sort': 'Trier',
    'Sort By': 'Trier par',
    'Source': 'Source',
    'Stage': 'Étape',
    'Stages': 'Étapes',
    'Start Date': 'Date de début',
    'Status': 'Statut',
    'Subject': 'Sujet',
    'Submit': 'Soumettre',
    'Success': 'Succès',
    'Summary': 'Résumé',
    'Tags': 'Tags',
    'Task': 'Tâche',
    'Task Status': 'Statut de la tâche',
    'Tasks': 'Tâches',
    'Team': 'Équipe',
    'Territory': 'Territoire',
    'Text': 'Texte',
    'Time': 'Heure',
    'Timeline': 'Chronologie',
    'Title': 'Titre',
    'To': 'À',
    'Today': 'Aujourd\'hui',
    'Total': 'Total',
    'Type': 'Type',
    'Unassigned': 'Non assigné',
    'Update': 'Mettre à jour',
    'Updated': 'Mis à jour',
    'Upload': 'Télécharger',
    'User': 'Utilisateur',
    'Users': 'Utilisateurs',
    'Valid': 'Valide',
    'Value': 'Valeur',
    'View': 'Voir',
    'View All': 'Voir tout',
    'View Details': 'Voir les détails',
    'Views': 'Vues',
    'Warning': 'Avertissement',
    'Website': 'Site web',
    'Won': 'Gagné',
    'Yes': 'Oui',
    'Yesterday': 'Hier',

    # Specific messages and phrases
    'No {0} found': 'Aucun {0} trouvé',
    'Are you sure you want to delete this {0}?': 'Êtes-vous sûr de vouloir supprimer ce {0} ?',
    'Select a {0}': 'Sélectionner un {0}',
    'Create a new {0}': 'Créer un nouveau {0}',
    'Edit {0}': 'Modifier {0}',
    'Delete {0}': 'Supprimer {0}',
    '{0} deleted successfully': '{0} supprimé avec succès',
    '{0} created successfully': '{0} créé avec succès',
    '{0} updated successfully': '{0} mis à jour avec succès',
    'Loading {0}...': 'Chargement de {0}...',
    'Showing {0} of {1}': 'Affichage de {0} sur {1}',
    '{0} selected': '{0} sélectionné',
    'No {0} selected': 'Aucun {0} sélectionné',

    # Time-related
    'a few seconds ago': 'il y a quelques secondes',
    'a minute ago': 'il y a une minute',
    'an hour ago': 'il y a une heure',
    'a day ago': 'il y a un jour',
    'a week ago': 'il y a une semaine',
    'a month ago': 'il y a un mois',
    'a year ago': 'il y a un an',
    '{0} seconds ago': 'il y a {0} secondes',
    '{0} minutes ago': 'il y a {0} minutes',
    '{0} hours ago': 'il y a {0} heures',
    '{0} days ago': 'il y a {0} jours',
    '{0} weeks ago': 'il y a {0} semaines',
    '{0} months ago': 'il y a {0} mois',
    '{0} years ago': 'il y a {0} années',
    'just now': 'à l\'instant',
    'in {0} seconds': 'dans {0} secondes',
    'in {0} minutes': 'dans {0} minutes',
    'in {0} hours': 'dans {0} heures',
    'in {0} days': 'dans {0} jours',
    'in a few seconds': 'dans quelques secondes',
    'in a minute': 'dans une minute',
    'in an hour': 'dans une heure',
    'in a day': 'dans un jour',
    'This Week': 'Cette semaine',
    'This Month': 'Ce mois-ci',
    'This Quarter': 'Ce trimestre',
    'This Year': 'Cette année',
    'Last Week': 'La semaine dernière',
    'Last Month': 'Le mois dernier',
    'Last Quarter': 'Le trimestre dernier',
    'Last Year': 'L\'année dernière',
    'Next Week': 'La semaine prochaine',
    'Next Month': 'Le mois prochain',
    'Next Quarter': 'Le trimestre prochain',
    'Next Year': 'L\'année prochaine',

    # Additional CRM-specific terms
    'Annual Revenue': 'Chiffre d\'affaires annuel',
    'No. of Employees': 'Nombre d\'employés',
    'Job Title': 'Titre du poste',
    'Department': 'Département',
    'Reports To': 'Rapporte à',
    'Decision Maker': 'Décideur',
    'Buying Role': 'Rôle d\'acheteur',
    'Email Opt Out': 'Désinscription email',
    'Unsubscribed': 'Désabonné',
    'Do Not Disturb': 'Ne pas déranger',
    'Salutation': 'Civilité',
    'Gender': 'Sexe',
    'Birthday': 'Anniversaire',
    'LinkedIn': 'LinkedIn',
    'Twitter': 'Twitter',
    'Facebook': 'Facebook',
    'Instagram': 'Instagram',
    'Social Media': 'Réseaux sociaux',
    'Primary Contact': 'Contact principal',
    'Billing Address': 'Adresse de facturation',
    'Shipping Address': 'Adresse de livraison',
    'Street': 'Rue',
    'City': 'Ville',
    'State': 'État',
    'Postal Code': 'Code postal',
    'Country': 'Pays',
    'Address Line 1': 'Adresse ligne 1',
    'Address Line 2': 'Adresse ligne 2',
    'Zip Code': 'Code postal',
    'Campaign': 'Campagne',
    'Campaign Name': 'Nom de la campagne',
    'Medium': 'Support',
    'Referral Source': 'Source de référence',
    'Lead Type': 'Type de prospect',
    'Opportunity': 'Opportunité',
    'Opportunities': 'Opportunités',
    'Sales Stage': 'Étape de vente',
    'Quotation': 'Devis',
    'Proposal': 'Proposition',
    'Contract': 'Contrat',
    'Invoice': 'Facture',
    'Payment': 'Paiement',
    'Product': 'Produit',
    'Products': 'Produits',
    'Service': 'Service',
    'Services': 'Services',
    'Price': 'Prix',
    'Quantity': 'Quantité',
    'Discount': 'Remise',
    'Tax': 'Taxe',
    'Subtotal': 'Sous-total',
    'Grand Total': 'Total général',
    'Payment Terms': 'Conditions de paiement',
    'Delivery Date': 'Date de livraison',
    'Valid Till': 'Valide jusqu\'au',
    'Terms and Conditions': 'Conditions générales',
    'Signature': 'Signature',
    'Approved': 'Approuvé',
    'Rejected': 'Rejeté',
    'Submitted': 'Soumis',
    'On Hold': 'En attente',
    'Ordered': 'Commandé',
    'Delivered': 'Livré',
    'Cancelled': 'Annulé',
    'Returned': 'Retourné',
    'Refunded': 'Remboursé',
    'Partially Paid': 'Partiellement payé',
    'Fully Paid': 'Entièrement payé',
    'Overdue': 'En retard',
    'Not Contacted': 'Non contacté',
    'Attempted to Contact': 'Tentative de contact',
    'Contact in Future': 'Contacter ultérieurement',
    'Contacted': 'Contacté',
    'Junk Lead': 'Prospect indésirable',
    'Lost Lead': 'Prospect perdu',
    'Not Interested': 'Pas intéressé',
    'Unqualified': 'Non qualifié',
    'Interested': 'Intéressé',
    'Quote Requested': 'Devis demandé',
    'Quotation Sent': 'Devis envoyé',
    'In Discussion': 'En discussion',
    'Negotiation': 'Négociation',
    'Deal Won': 'Affaire gagnée',
    'Deal Lost': 'Affaire perdue',
    'Cold': 'Froid',
    'Warm': 'Tiède',
    'Hot': 'Chaud',
    'High': 'Élevé',
    'Medium': 'Moyen',
    'Low': 'Faible',
    'Critical': 'Critique',
    'Urgent': 'Urgent',
    'Normal': 'Normal',
    'To Do': 'À faire',
    'Doing': 'En cours',
    'Overdue Task': 'Tâche en retard',
    'Completed Task': 'Tâche terminée',
    'Cancelled Task': 'Tâche annulée',
    'Incoming Call': 'Appel entrant',
    'Outgoing Call': 'Appel sortant',
    'Missed Call': 'Appel manqué',
    'Completed Call': 'Appel terminé',
    'Busy': 'Occupé',
    'No Answer': 'Pas de réponse',
    'Wrong Number': 'Mauvais numéro',
    'Left Voicemail': 'Message vocal laissé',
    'Connected': 'Connecté',
    'Meeting Scheduled': 'Réunion planifiée',
    'Meeting Completed': 'Réunion terminée',
    'Meeting Cancelled': 'Réunion annulée',
    'Email Sent': 'Email envoyé',
    'Email Received': 'Email reçu',
    'Email Opened': 'Email ouvert',
    'Email Clicked': 'Email cliqué',
    'Email Bounced': 'Email rejeté',
    'Unsubscribe': 'Se désabonner',
    'Subscribe': 'S\'abonner',
    'Newsletter': 'Newsletter',
    'Announcement': 'Annonce',
    'Promotion': 'Promotion',
    'Follow-up Required': 'Suivi requis',
    'Callback Requested': 'Rappel demandé',
    'Information Requested': 'Information demandée',
    'Proposal Requested': 'Proposition demandée',
    'Demo Scheduled': 'Démo planifiée',
    'Demo Completed': 'Démo terminée',
    'Trial Started': 'Essai démarré',
    'Trial Expired': 'Essai expiré',
    'Converted to Customer': 'Converti en client',
    'First Contact': 'Premier contact',
    'Qualification': 'Qualification',
    'Needs Analysis': 'Analyse des besoins',
    'Proposal/Price Quote': 'Proposition/Devis',
    'Negotiation/Review': 'Négociation/Revue',
    'Closed Won': 'Fermé gagné',
    'Closed Lost': 'Fermé perdu',
    'Prospecting': 'Prospection',
    'Discovery': 'Découverte',
    'Proposal': 'Proposition',
    'Verbal Commitment': 'Engagement verbal',
    'Contract Sent': 'Contrat envoyé',
    'Contract Signed': 'Contrat signé',

    # UI elements
    'Search for': 'Rechercher',
    'Filter by status': 'Filtrer par statut',
    'Filter by owner': 'Filtrer par propriétaire',
    'Filter by date': 'Filtrer par date',
    'Sort by name': 'Trier par nom',
    'Sort by date': 'Trier par date',
    'Sort by value': 'Trier par valeur',
    'Sort ascending': 'Tri croissant',
    'Sort descending': 'Tri décroissant',
    'View as list': 'Afficher en liste',
    'View as grid': 'Afficher en grille',
    'View as kanban': 'Afficher en kanban',
    'View as calendar': 'Afficher en calendrier',
    'View as table': 'Afficher en tableau',
    'Columns': 'Colonnes',
    'Show/Hide Columns': 'Afficher/Masquer les colonnes',
    'Customize': 'Personnaliser',
    'Customize View': 'Personnaliser la vue',
    'Save View': 'Enregistrer la vue',
    'Reset View': 'Réinitialiser la vue',
    'Default View': 'Vue par défaut',
    'Bulk Actions': 'Actions groupées',
    'Bulk Edit': 'Modification groupée',
    'Bulk Delete': 'Suppression groupée',
    'Bulk Assign': 'Attribution groupée',
    'Select items': 'Sélectionner des éléments',
    'items selected': 'éléments sélectionnés',
    'Deselect All': 'Tout désélectionner',
    'Actions': 'Actions',
    'More Actions': 'Plus d\'actions',
    'Quick Actions': 'Actions rapides',
    'Related Records': 'Enregistrements liés',
    'Related Activities': 'Activités liées',
    'Activity Log': 'Journal d\'activité',
    'Audit Trail': 'Piste d\'audit',
    'Change Log': 'Journal des modifications',
    'Version History': 'Historique des versions',
    'Attachments': 'Pièces jointes',
    'Add Attachment': 'Ajouter une pièce jointe',
    'Upload File': 'Télécharger un fichier',
    'Download File': 'Télécharger le fichier',
    'Delete File': 'Supprimer le fichier',
    'File Name': 'Nom du fichier',
    'File Size': 'Taille du fichier',
    'File Type': 'Type de fichier',
    'Uploaded By': 'Téléchargé par',
    'Uploaded On': 'Téléchargé le',
    'Comments/Notes': 'Commentaires/Notes',
    'Add a comment or note': 'Ajouter un commentaire ou une note',
    'Post Comment': 'Publier le commentaire',
    'Edit Comment': 'Modifier le commentaire',
    'Delete Comment': 'Supprimer le commentaire',
    'Reply': 'Répondre',
    'Show Replies': 'Afficher les réponses',
    'Hide Replies': 'Masquer les réponses',
    'Private Note': 'Note privée',
    'Public Comment': 'Commentaire public',
    'Internal Note': 'Note interne',
    'Customer Facing': 'Visible par le client',
    'Mentions': 'Mentions',
    'Tagged': 'Tagué',
    'Pinned': 'Épinglé',
    'Mark as Important': 'Marquer comme important',
    'Mark as Complete': 'Marquer comme terminé',
    'Mark as Incomplete': 'Marquer comme incomplet',
    'Follow': 'Suivre',
    'Unfollow': 'Ne plus suivre',
    'Following': 'Suivi',
    'Followers': 'Abonnés',
    'Watching': 'En observation',
    'Subscribers': 'Abonnés',
    'Share with': 'Partager avec',
    'Shared with': 'Partagé avec',
    'Permissions': 'Permissions',
    'Can View': 'Peut voir',
    'Can Edit': 'Peut modifier',
    'Can Delete': 'Peut supprimer',
    'Can Share': 'Peut partager',
    'Full Access': 'Accès complet',
    'Read Only': 'Lecture seule',
    'No Access': 'Pas d\'accès',
    'Owner': 'Propriétaire',
    'Collaborators': 'Collaborateurs',
    'Transfer Ownership': 'Transférer la propriété',
    'Change Owner': 'Changer le propriétaire',

    # Error and success messages
    'Please fill in all required fields': 'Veuillez remplir tous les champs obligatoires',
    'Invalid email address': 'Adresse email invalide',
    'Invalid phone number': 'Numéro de téléphone invalide',
    'Invalid date': 'Date invalide',
    'Date must be in the future': 'La date doit être dans le futur',
    'Date must be in the past': 'La date doit être dans le passé',
    'Value must be greater than 0': 'La valeur doit être supérieure à 0',
    'Value must be between {0} and {1}': 'La valeur doit être entre {0} et {1}',
    'This field is required': 'Ce champ est obligatoire',
    'Please select an option': 'Veuillez sélectionner une option',
    'Please enter a valid value': 'Veuillez entrer une valeur valide',
    'Changes saved successfully': 'Modifications enregistrées avec succès',
    'Failed to save changes': 'Échec de l\'enregistrement des modifications',
    'Record created successfully': 'Enregistrement créé avec succès',
    'Failed to create record': 'Échec de la création de l\'enregistrement',
    'Record updated successfully': 'Enregistrement mis à jour avec succès',
    'Failed to update record': 'Échec de la mise à jour de l\'enregistrement',
    'Record deleted successfully': 'Enregistrement supprimé avec succès',
    'Failed to delete record': 'Échec de la suppression de l\'enregistrement',
    'No changes to save': 'Aucune modification à enregistrer',
    'Are you sure you want to continue?': 'Êtes-vous sûr de vouloir continuer ?',
    'This action cannot be undone': 'Cette action ne peut pas être annulée',
    'Confirm deletion': 'Confirmer la suppression',
    'Confirm action': 'Confirmer l\'action',
    'Operation completed successfully': 'Opération terminée avec succès',
    'Operation failed': 'Opération échouée',
    'An error occurred': 'Une erreur s\'est produite',
    'Please try again': 'Veuillez réessayer',
    'Loading data...': 'Chargement des données...',
    'Saving...': 'Enregistrement...',
    'Processing...': 'Traitement...',
    'Please wait...': 'Veuillez patienter...',
    'Network error': 'Erreur réseau',
    'Connection lost': 'Connexion perdue',
    'Reconnecting...': 'Reconnexion...',
    'Session expired': 'Session expirée',
    'Please login again': 'Veuillez vous reconnecter',
    'Access denied': 'Accès refusé',
    'Permission denied': 'Permission refusée',
    'Not found': 'Non trouvé',
    'Page not found': 'Page non trouvée',
    'Record not found': 'Enregistrement non trouvé',
    'No data available': 'Aucune donnée disponible',
    'Nothing to display': 'Rien à afficher',
    'Empty list': 'Liste vide',
    'No items': 'Aucun élément',
    'Start by creating a new {0}': 'Commencez par créer un nouveau {0}',
    'Click the button above to get started': 'Cliquez sur le bouton ci-dessus pour commencer',

    # Dashboard and Analytics
    'Overview': 'Aperçu',
    'Statistics': 'Statistiques',
    'Metrics': 'Métriques',
    'KPIs': 'KPI',
    'Performance': 'Performance',
    'Trends': 'Tendances',
    'Comparison': 'Comparaison',
    'Year over Year': 'Année après année',
    'Month over Month': 'Mois après mois',
    'Quarter over Quarter': 'Trimestre après trimestre',
    'vs. Last Period': 'vs. Période précédente',
    'Growth Rate': 'Taux de croissance',
    'Conversion Rate': 'Taux de conversion',
    'Win Rate': 'Taux de réussite',
    'Close Rate': 'Taux de clôture',
    'Average Deal Size': 'Taille moyenne de l\'affaire',
    'Average Sales Cycle': 'Cycle de vente moyen',
    'Sales Velocity': 'Vélocité des ventes',
    'Pipeline Value': 'Valeur du pipeline',
    'Forecast': 'Prévision',
    'Quota': 'Quota',
    'Target vs Actual': 'Objectif vs Réel',
    'Achievement': 'Réalisation',
    'Top Performers': 'Meilleurs performers',
    'Bottom Performers': 'Performers les moins bons',
    'Leaderboard': 'Classement',
    'Sales by': 'Ventes par',
    'Leads by': 'Prospects par',
    'Deals by': 'Affaires par',
    'Revenue by': 'Revenu par',
    'Activity by': 'Activité par',
    'by Stage': 'par étape',
    'by Status': 'par statut',
    'by Owner': 'par propriétaire',
    'by Source': 'par source',
    'by Industry': 'par industrie',
    'by Territory': 'par territoire',
    'by Product': 'par produit',
    'by Date': 'par date',
    'by Month': 'par mois',
    'by Quarter': 'par trimestre',
    'by Year': 'par année',
    'Chart Type': 'Type de graphique',
    'Line Chart': 'Graphique linéaire',
    'Bar Chart': 'Graphique à barres',
    'Pie Chart': 'Graphique circulaire',
    'Donut Chart': 'Graphique en anneau',
    'Area Chart': 'Graphique en aires',
    'Scatter Plot': 'Nuage de points',
    'Heat Map': 'Carte thermique',
    'Funnel': 'Entonnoir',
    'Gauge': 'Jauge',
    'Data Range': 'Plage de données',
    'Date Range': 'Plage de dates',
    'Custom Date Range': 'Plage de dates personnalisée',
    'From Date': 'Date de début',
    'To Date': 'Date de fin',
    'Apply Date Range': 'Appliquer la plage de dates',
    'Reset to Default': 'Réinitialiser par défaut',
    'Refresh Data': 'Actualiser les données',
    'Export Data': 'Exporter les données',
    'Export to Excel': 'Exporter vers Excel',
    'Export to CSV': 'Exporter vers CSV',
    'Export to PDF': 'Exporter vers PDF',
    'Print': 'Imprimer',
    'Share Report': 'Partager le rapport',
    'Schedule Report': 'Planifier le rapport',
    'Email Report': 'Envoyer le rapport par email',
    'Download Report': 'Télécharger le rapport',

    # Settings and Configuration
    'Account Settings': 'Paramètres du compte',
    'Profile Settings': 'Paramètres du profil',
    'Preferences': 'Préférences',
    'Email Settings': 'Paramètres email',
    'Notification Settings': 'Paramètres de notification',
    'Privacy Settings': 'Paramètres de confidentialité',
    'Security Settings': 'Paramètres de sécurité',
    'Integration Settings': 'Paramètres d\'intégration',
    'API Settings': 'Paramètres API',
    'General Settings': 'Paramètres généraux',
    'System Settings': 'Paramètres système',
    'User Management': 'Gestion des utilisateurs',
    'Role Management': 'Gestion des rôles',
    'Permission Management': 'Gestion des permissions',
    'Team Management': 'Gestion de l\'équipe',
    'Territory Management': 'Gestion du territoire',
    'Pipeline Management': 'Gestion du pipeline',
    'Stage Management': 'Gestion des étapes',
    'Field Customization': 'Personnalisation des champs',
    'Custom Fields': 'Champs personnalisés',
    'Page Layout': 'Mise en page',
    'Email Templates': 'Modèles d\'email',
    'Document Templates': 'Modèles de document',
    'Automation Rules': 'Règles d\'automatisation',
    'Workflow Rules': 'Règles de flux de travail',
    'Assignment Rules': 'Règles d\'attribution',
    'Validation Rules': 'Règles de validation',
    'Email Notifications': 'Notifications par email',
    'Push Notifications': 'Notifications push',
    'SMS Notifications': 'Notifications SMS',
    'Web Notifications': 'Notifications web',
    'Alert Rules': 'Règles d\'alerte',
    'Reminders': 'Rappels',
    'Task Reminders': 'Rappels de tâche',
    'Event Reminders': 'Rappels d\'événement',
    'Follow-up Reminders': 'Rappels de suivi',
    'Data Import': 'Import de données',
    'Data Export': 'Export de données',
    'Data Backup': 'Sauvegarde des données',
    'Data Migration': 'Migration des données',
    'Bulk Import': 'Import groupé',
    'Import from CSV': 'Importer depuis CSV',
    'Import from Excel': 'Importer depuis Excel',
    'Map Fields': 'Mapper les champs',
    'Field Mapping': 'Mappage des champs',
    'Preview Import': 'Aperçu de l\'import',
    'Start Import': 'Démarrer l\'import',
    'Import Status': 'Statut de l\'import',
    'Import History': 'Historique des imports',
    'Sync Status': 'Statut de synchronisation',
    'Last Synced': 'Dernière synchronisation',
    'Sync Now': 'Synchroniser maintenant',
    'Auto Sync': 'Synchronisation automatique',
    'Sync Settings': 'Paramètres de synchronisation',

    # Help and Documentation
    'Help Center': 'Centre d\'aide',
    'Documentation': 'Documentation',
    'User Guide': 'Guide de l\'utilisateur',
    'Getting Started': 'Premiers pas',
    'Tutorials': 'Tutoriels',
    'Video Tutorials': 'Tutoriels vidéo',
    'FAQs': 'FAQ',
    'Knowledge Base': 'Base de connaissances',
    'Support': 'Support',
    'Contact Support': 'Contacter le support',
    'Submit a Ticket': 'Soumettre un ticket',
    'Report a Bug': 'Signaler un bug',
    'Request a Feature': 'Demander une fonctionnalité',
    'Send Feedback': 'Envoyer un retour',
    'Release Notes': 'Notes de version',
    'What\'s New': 'Nouveautés',
    'System Status': 'Statut du système',
    'Service Status': 'Statut du service',
    'Maintenance Schedule': 'Planning de maintenance',
    'Terms of Service': 'Conditions d\'utilisation',
    'Privacy Policy': 'Politique de confidentialité',
    'Cookie Policy': 'Politique des cookies',
    'Legal': 'Mentions légales',
    'License': 'Licence',
    'Credits': 'Crédits',
    'Powered by': 'Propulsé par',
    'Version': 'Version',
    'Build': 'Build',
    'Copyright': 'Copyright',
    'All rights reserved': 'Tous droits réservés',

    # Mobile and Responsive
    'Mobile View': 'Vue mobile',
    'Desktop View': 'Vue bureau',
    'Tablet View': 'Vue tablette',
    'Responsive Design': 'Design responsive',
    'Touch Gestures': 'Gestes tactiles',
    'Swipe': 'Glisser',
    'Tap': 'Appuyer',
    'Long Press': 'Appui long',
    'Pinch to Zoom': 'Pincer pour zoomer',
    'Pull to Refresh': 'Tirer pour actualiser',

    # Additional field labels
    'Facebook URL': 'URL Facebook',
    'Twitter Handle': 'Compte Twitter',
    'LinkedIn URL': 'URL LinkedIn',
    'Instagram Handle': 'Compte Instagram',
    'Skype ID': 'ID Skype',
    'WhatsApp': 'WhatsApp',
    'WeChat': 'WeChat',
    'Telegram': 'Telegram',
    'Assistant': 'Assistant',
    'Assistant Phone': 'Téléphone de l\'assistant',
    'Assistant Email': 'Email de l\'assistant',
    'Reporting Manager': 'Responsable hiérarchique',
    'Parent Organization': 'Organisation parente',
    'Subsidiary': 'Filiale',
    'Headquarters': 'Siège social',
    'Branch': 'Branche',
    'Branches': 'Branches',
    'NAICS Code': 'Code NAICS',
    'SIC Code': 'Code SIC',
    'Tax ID': 'Numéro fiscal',
    'VAT Number': 'Numéro de TVA',
    'Registration Number': 'Numéro d\'enregistrement',
    'Stock Symbol': 'Symbole boursier',
    'Ticker Symbol': 'Symbole boursier',
    'Founded': 'Fondé',
    'Founded Year': 'Année de fondation',
    'Business Type': 'Type d\'entreprise',
    'Ownership': 'Propriété',
    'Public': 'Public',
    'Private': 'Privé',
    'Partnership': 'Partenariat',
    'Corporation': 'Société',
    'LLC': 'SARL',
    'Non-Profit': 'Sans but lucratif',
    'Government': 'Gouvernement',
    'Preferred Contact Method': 'Méthode de contact préférée',
    'Best Time to Call': 'Meilleur moment pour appeler',
    'Time Zone': 'Fuseau horaire',
    'Working Hours': 'Heures de travail',
    'Office Hours': 'Heures de bureau',
    'Business Hours': 'Heures d\'ouverture',
    'Holiday Schedule': 'Planning des jours fériés',
    'Out of Office': 'Absence du bureau',
    'Vacation': 'Vacances',
    'Sick Leave': 'Congé maladie',
    'Maternity Leave': 'Congé maternité',
    'Paternity Leave': 'Congé paternité',
    'Personal Leave': 'Congé personnel',
    'Sabbatical': 'Sabbatique',

    # Additional status and states
    'Pre-Qualified': 'Pré-qualifié',
    'SQL (Sales Qualified Lead)': 'SQL (Prospect qualifié pour la vente)',
    'MQL (Marketing Qualified Lead)': 'MQL (Prospect qualifié par le marketing)',
    'Working': 'En cours de traitement',
    'Nurturing': 'En cours de développement',
    'Re-engaged': 'Ré-engagé',
    'Recycled': 'Recyclé',
    'Archived': 'Archivé',
    'Spam': 'Spam',
    'Bounced': 'Rejeté',
    'Opt Out': 'Désinscription',
    'Do Not Call': 'Ne pas appeler',
    'Do Not Email': 'Ne pas envoyer d\'email',
    'Do Not SMS': 'Ne pas envoyer de SMS',
    'Do Not Mail': 'Ne pas envoyer de courrier',
    'Invalid Email': 'Email invalide',
    'Invalid Phone': 'Téléphone invalide',
    'Deceased': 'Décédé',
    'Duplicate': 'Doublon',
    'Test Record': 'Enregistrement de test',
    'Blacklisted': 'Liste noire',
    'Whitelisted': 'Liste blanche',
}

def process_po_file(input_file, output_file):
    """
    Process PO file and translate all empty msgstr entries.
    """
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    translated_count = 0
    i = 0

    while i < len(lines):
        line = lines[i]

        # Check if this is a msgid line
        if line.startswith('msgid '):
            # Extract msgid value
            msgid_match = re.match(r'msgid "(.*)"', line)
            if msgid_match:
                msgid_value = msgid_match.group(1)

                # Check if next line is an empty msgstr
                if i + 1 < len(lines) and lines[i + 1].strip() == 'msgstr ""':
                    # Try to find a translation
                    if msgid_value in TRANSLATIONS:
                        translation = TRANSLATIONS[msgid_value]
                        # Replace the empty msgstr with the translation
                        lines[i + 1] = f'msgstr "{translation}"\n'
                        translated_count += 1

        i += 1

    # Write the updated content
    with open(output_file, 'w', encoding='utf-8') as f:
        f.writelines(lines)

    return translated_count

if __name__ == '__main__':
    input_file = '/Users/jeremy/GitHub/crm/crm/locale/fr.po'
    output_file = '/Users/jeremy/GitHub/crm/crm/locale/fr.po'

    print("Starting translation process...")
    print(f"Reading from: {input_file}")

    translated = process_po_file(input_file, output_file)

    print(f"\nTranslation complete!")
    print(f"Successfully translated: {translated} strings")
    print(f"Output saved to: {output_file}")
