#!/usr/bin/env python3
"""
Script to translate empty msgstr entries in a PO file to French.
Preserves all placeholders, HTML tags, and formatting.
"""

import re
import sys

# CRM terminology mapping
CRM_TERMS = {
    'Lead': 'Prospect',
    'Leads': 'Prospects',
    'Deal': 'Affaire',
    'Deals': 'Affaires',
    'Contact': 'Contact',
    'Contacts': 'Contacts',
    'Organization': 'Organisation',
    'Organizations': 'Organisations',
    'Task': 'Tâche',
    'Tasks': 'Tâches',
    'Call Log': 'Journal d\'appel',
    'Call Logs': 'Journaux d\'appel',
    'Pipeline': 'Pipeline',
    'Pipelines': 'Pipelines',
    'Stage': 'Étape',
    'Stages': 'Étapes',
    'Won': 'Gagné',
    'Lost': 'Perdu',
}

# Common translations for CRM context
TRANSLATIONS = {
    # Actions
    'Add': 'Ajouter',
    'Edit': 'Modifier',
    'Delete': 'Supprimer',
    'Save': 'Enregistrer',
    'Cancel': 'Annuler',
    'Create': 'Créer',
    'Update': 'Mettre à jour',
    'Remove': 'Retirer',
    'Close': 'Fermer',
    'Open': 'Ouvrir',
    'View': 'Voir',
    'Search': 'Rechercher',
    'Filter': 'Filtrer',
    'Sort': 'Trier',
    'Export': 'Exporter',
    'Import': 'Importer',
    'Refresh': 'Actualiser',
    'Clear': 'Effacer',
    'Select': 'Sélectionner',
    'Upload': 'Télécharger',
    'Download': 'Télécharger',
    'Send': 'Envoyer',
    'Submit': 'Soumettre',
    'Assign': 'Assigner',
    'Convert': 'Convertir',
    'Merge': 'Fusionner',
    'Duplicate': 'Dupliquer',
    'Archive': 'Archiver',
    'Restore': 'Restaurer',

    # Status
    'Active': 'Actif',
    'Inactive': 'Inactif',
    'Pending': 'En attente',
    'Completed': 'Terminé',
    'In Progress': 'En cours',
    'New': 'Nouveau',
    'Open': 'Ouvert',
    'Closed': 'Fermé',
    'Cancelled': 'Annulé',
    'Draft': 'Brouillon',
    'Published': 'Publié',

    # Common fields
    'Name': 'Nom',
    'Email': 'Email',
    'Phone': 'Téléphone',
    'Mobile': 'Mobile',
    'Address': 'Adresse',
    'City': 'Ville',
    'State': 'État',
    'Country': 'Pays',
    'Postal Code': 'Code postal',
    'Description': 'Description',
    'Notes': 'Notes',
    'Date': 'Date',
    'Time': 'Heure',
    'Status': 'Statut',
    'Priority': 'Priorité',
    'Type': 'Type',
    'Owner': 'Propriétaire',
    'Assigned To': 'Assigné à',
    'Created': 'Créé',
    'Modified': 'Modifié',
    'Created By': 'Créé par',
    'Modified By': 'Modifié par',
    'Total': 'Total',
    'Amount': 'Montant',
    'Value': 'Valeur',
    'Currency': 'Devise',
    'Website': 'Site web',
    'Company': 'Société',
    'Title': 'Titre',
    'First Name': 'Prénom',
    'Last Name': 'Nom de famille',
    'Full Name': 'Nom complet',
    'Source': 'Source',
    'Industry': 'Industrie',
    'Territory': 'Territoire',
    'Annual Revenue': 'Chiffre d\'affaires annuel',
    'Number of Employees': 'Nombre d\'employés',
    'Due Date': 'Date d\'échéance',
    'Completed Date': 'Date de fin',
    'Start Date': 'Date de début',
    'End Date': 'Date de fin',
    'Expected Closing': 'Clôture prévue',
    'Closing Date': 'Date de clôture',
    'Probability': 'Probabilité',
    'Next Action': 'Prochaine action',
    'Next Action Date': 'Date de prochaine action',

    # Messages and labels
    'Yes': 'Oui',
    'No': 'Non',
    'All': 'Tout',
    'None': 'Aucun',
    'Loading': 'Chargement',
    'Error': 'Erreur',
    'Success': 'Succès',
    'Warning': 'Avertissement',
    'Info': 'Information',
    'Confirmation': 'Confirmation',
    'Required': 'Obligatoire',
    'Optional': 'Optionnel',
    'Details': 'Détails',
    'Settings': 'Paramètres',
    'Preferences': 'Préférences',
    'Profile': 'Profil',
    'Help': 'Aide',
    'About': 'À propos',
    'Version': 'Version',
    'More': 'Plus',
    'Less': 'Moins',
    'Show': 'Afficher',
    'Hide': 'Masquer',
    'Expand': 'Développer',
    'Collapse': 'Réduire',
    'Previous': 'Précédent',
    'Next': 'Suivant',
    'First': 'Premier',
    'Last': 'Dernier',
    'Page': 'Page',
    'of': 'de',
    'to': 'à',
    'From': 'De',
    'To': 'À',
    'Subject': 'Sujet',
    'Message': 'Message',
    'Comment': 'Commentaire',
    'Comments': 'Commentaires',
    'Activity': 'Activité',
    'Activities': 'Activités',
    'History': 'Historique',
    'Timeline': 'Chronologie',
    'Attachment': 'Pièce jointe',
    'Attachments': 'Pièces jointes',
    'Tag': 'Tag',
    'Tags': 'Tags',
    'Category': 'Catégorie',
    'Categories': 'Catégories',
    'Custom': 'Personnalisé',
    'Default': 'Par défaut',
    'Standard': 'Standard',
    'Advanced': 'Avancé',
    'Basic': 'Basique',
    'General': 'Général',
    'Other': 'Autre',
    'Others': 'Autres',
    'Related': 'Lié',
    'Recent': 'Récent',
    'Today': 'Aujourd\'hui',
    'Yesterday': 'Hier',
    'Tomorrow': 'Demain',
    'This Week': 'Cette semaine',
    'Last Week': 'La semaine dernière',
    'Next Week': 'La semaine prochaine',
    'This Month': 'Ce mois-ci',
    'Last Month': 'Le mois dernier',
    'Next Month': 'Le mois prochain',
    'This Year': 'Cette année',
    'Last Year': 'L\'année dernière',
    'Next Year': 'L\'année prochaine',
    'Custom Range': 'Période personnalisée',
    'Dashboard': 'Tableau de bord',
    'Reports': 'Rapports',
    'Analytics': 'Analyses',
    'Chart': 'Graphique',
    'Table': 'Tableau',
    'List': 'Liste',
    'Grid': 'Grille',
    'Calendar': 'Calendrier',
    'Map': 'Carte',
    'User': 'Utilisateur',
    'Users': 'Utilisateurs',
    'Role': 'Rôle',
    'Roles': 'Rôles',
    'Permission': 'Permission',
    'Permissions': 'Permissions',
    'Access': 'Accès',
    'Public': 'Public',
    'Private': 'Privé',
    'Shared': 'Partagé',
    'Team': 'Équipe',
    'Teams': 'Équipes',
    'Group': 'Groupe',
    'Groups': 'Groupes',
    'Department': 'Département',
    'Departments': 'Départements',
    'Manager': 'Responsable',
    'Employee': 'Employé',
    'Employees': 'Employés',
    'Sales': 'Ventes',
    'Marketing': 'Marketing',
    'Support': 'Support',
    'Customer': 'Client',
    'Customers': 'Clients',
    'Vendor': 'Fournisseur',
    'Vendors': 'Fournisseurs',
    'Partner': 'Partenaire',
    'Partners': 'Partenaires',
    'Product': 'Produit',
    'Products': 'Produits',
    'Service': 'Service',
    'Services': 'Services',
    'Price': 'Prix',
    'Discount': 'Remise',
    'Tax': 'Taxe',
    'Quantity': 'Quantité',
    'Unit': 'Unité',
    'Item': 'Article',
    'Items': 'Articles',
    'Quotation': 'Devis',
    'Quotations': 'Devis',
    'Order': 'Commande',
    'Orders': 'Commandes',
    'Invoice': 'Facture',
    'Invoices': 'Factures',
    'Payment': 'Paiement',
    'Payments': 'Paiements',
    'Transaction': 'Transaction',
    'Transactions': 'Transactions',
    'Balance': 'Solde',
    'Revenue': 'Revenu',
    'Expense': 'Dépense',
    'Expenses': 'Dépenses',
    'Profit': 'Bénéfice',
    'Loss': 'Perte',
    'Budget': 'Budget',
    'Forecast': 'Prévision',
    'Target': 'Objectif',
    'Actual': 'Réel',
    'Variance': 'Écart',
    'Growth': 'Croissance',
    'Decline': 'Baisse',
    'Trend': 'Tendance',
    'Average': 'Moyenne',
    'Minimum': 'Minimum',
    'Maximum': 'Maximum',
    'Sum': 'Somme',
    'Count': 'Nombre',
    'Percentage': 'Pourcentage',
    'Rate': 'Taux',
    'Ratio': 'Ratio',
    'Score': 'Score',
    'Rank': 'Rang',
    'Level': 'Niveau',
    'High': 'Élevé',
    'Medium': 'Moyen',
    'Low': 'Faible',
    'Critical': 'Critique',
    'Urgent': 'Urgent',
    'Normal': 'Normal',
    'Hot': 'Chaud',
    'Warm': 'Tiède',
    'Cold': 'Froid',
    'Qualified': 'Qualifié',
    'Unqualified': 'Non qualifié',
    'Contacted': 'Contacté',
    'Not Contacted': 'Non contacté',
    'Converted': 'Converti',
    'Not Converted': 'Non converti',
    'Scheduled': 'Planifié',
    'Overdue': 'En retard',
    'On Track': 'En bonne voie',
    'At Risk': 'À risque',
    'Delayed': 'Retardé',
    'Meeting': 'Réunion',
    'Meetings': 'Réunions',
    'Call': 'Appel',
    'Calls': 'Appels',
    'Email': 'Email',
    'Emails': 'Emails',
    'SMS': 'SMS',
    'Chat': 'Chat',
    'Video Call': 'Appel vidéo',
    'Conference': 'Conférence',
    'Appointment': 'Rendez-vous',
    'Appointments': 'Rendez-vous',
    'Event': 'Événement',
    'Events': 'Événements',
    'Reminder': 'Rappel',
    'Reminders': 'Rappels',
    'Notification': 'Notification',
    'Notifications': 'Notifications',
    'Alert': 'Alerte',
    'Alerts': 'Alertes',
    'Log': 'Journal',
    'Logs': 'Journaux',
    'Audit': 'Audit',
    'Trail': 'Piste',
    'Record': 'Enregistrement',
    'Records': 'Enregistrements',
    'Entry': 'Entrée',
    'Entries': 'Entrées',
    'Field': 'Champ',
    'Fields': 'Champs',
    'Form': 'Formulaire',
    'Forms': 'Formulaires',
    'Template': 'Modèle',
    'Templates': 'Modèles',
    'Layout': 'Disposition',
    'Format': 'Format',
    'Style': 'Style',
    'Theme': 'Thème',
    'Color': 'Couleur',
    'Icon': 'Icône',
    'Image': 'Image',
    'File': 'Fichier',
    'Files': 'Fichiers',
    'Folder': 'Dossier',
    'Folders': 'Dossiers',
    'Document': 'Document',
    'Documents': 'Documents',
    'Link': 'Lien',
    'Links': 'Liens',
    'URL': 'URL',
    'Path': 'Chemin',
    'Location': 'Emplacement',
    'Position': 'Position',
    'Latitude': 'Latitude',
    'Longitude': 'Longitude',
    'Coordinates': 'Coordonnées',
    'Distance': 'Distance',
    'Duration': 'Durée',
    'Frequency': 'Fréquence',
    'Interval': 'Intervalle',
    'Period': 'Période',
    'Range': 'Plage',
    'Limit': 'Limite',
    'Offset': 'Décalage',
    'Size': 'Taille',
    'Width': 'Largeur',
    'Height': 'Hauteur',
    'Length': 'Longueur',
    'Weight': 'Poids',
    'Volume': 'Volume',
    'Area': 'Surface',
    'Capacity': 'Capacité',
    'Available': 'Disponible',
    'Unavailable': 'Indisponible',
    'Enabled': 'Activé',
    'Disabled': 'Désactivé',
    'Visible': 'Visible',
    'Hidden': 'Masqué',
    'Required': 'Requis',
    'Optional': 'Optionnel',
    'Valid': 'Valide',
    'Invalid': 'Invalide',
    'True': 'Vrai',
    'False': 'Faux',
    'On': 'Activé',
    'Off': 'Désactivé',
    'Checked': 'Coché',
    'Unchecked': 'Non coché',
    'Selected': 'Sélectionné',
    'Unselected': 'Non sélectionné',
    'Locked': 'Verrouillé',
    'Unlocked': 'Déverrouillé',
    'Read Only': 'Lecture seule',
    'Editable': 'Modifiable',
    'Mandatory': 'Obligatoire',
    'Not Set': 'Non défini',
    'Empty': 'Vide',
    'Full': 'Plein',
    'Partial': 'Partiel',
    'Complete': 'Complet',
    'Incomplete': 'Incomplet',
    'Approved': 'Approuvé',
    'Rejected': 'Rejeté',
    'Verified': 'Vérifié',
    'Unverified': 'Non vérifié',
    'Confirmed': 'Confirmé',
    'Unconfirmed': 'Non confirmé',
    'Valid Until': 'Valide jusqu\'au',
    'Expires On': 'Expire le',
    'Expired': 'Expiré',
    'Lifetime': 'À vie',
    'Permanent': 'Permanent',
    'Temporary': 'Temporaire',
    'Quick': 'Rapide',
    'Slow': 'Lent',
    'Fast': 'Rapide',
    'Immediate': 'Immédiat',
    'Delayed': 'Différé',
    'Automatic': 'Automatique',
    'Manual': 'Manuel',
    'System': 'Système',
    'Application': 'Application',
    'Module': 'Module',
    'Plugin': 'Plugin',
    'Extension': 'Extension',
    'Widget': 'Widget',
    'Component': 'Composant',
    'Feature': 'Fonctionnalité',
    'Function': 'Fonction',
    'Action': 'Action',
    'Operation': 'Opération',
    'Process': 'Processus',
    'Workflow': 'Flux de travail',
    'Automation': 'Automatisation',
    'Integration': 'Intégration',
    'API': 'API',
    'Webhook': 'Webhook',
    'Sync': 'Synchronisation',
    'Backup': 'Sauvegarde',
    'Restore': 'Restaurer',
    'Migration': 'Migration',
    'Upgrade': 'Mise à niveau',
    'Version': 'Version',
    'Release': 'Version',
    'Build': 'Build',
    'Deployment': 'Déploiement',
    'Environment': 'Environnement',
    'Production': 'Production',
    'Development': 'Développement',
    'Testing': 'Test',
    'Staging': 'Staging',
    'Local': 'Local',
    'Remote': 'Distant',
    'Server': 'Serveur',
    'Client': 'Client',
    'Database': 'Base de données',
    'Cache': 'Cache',
    'Session': 'Session',
    'Cookie': 'Cookie',
    'Token': 'Jeton',
    'Key': 'Clé',
    'Secret': 'Secret',
    'Password': 'Mot de passe',
    'Username': 'Nom d\'utilisateur',
    'Login': 'Connexion',
    'Logout': 'Déconnexion',
    'Sign In': 'Se connecter',
    'Sign Out': 'Se déconnecter',
    'Sign Up': 'S\'inscrire',
    'Register': 'S\'inscrire',
    'Account': 'Compte',
    'Profile': 'Profil',
    'Avatar': 'Avatar',
    'Bio': 'Bio',
    'Timezone': 'Fuseau horaire',
    'Language': 'Langue',
    'Locale': 'Localisation',
    'Format': 'Format',
    'Encoding': 'Encodage',
    'Character Set': 'Jeu de caractères',
    'Delimiter': 'Délimiteur',
    'Separator': 'Séparateur',
    'Quote': 'Guillemet',
    'Escape': 'Échappement',
    'Newline': 'Nouvelle ligne',
    'Tab': 'Tabulation',
    'Space': 'Espace',
    'Blank': 'Vide',
    'Null': 'Null',
    'Undefined': 'Indéfini',
    'Unknown': 'Inconnu',
    'Not Available': 'Non disponible',
    'Not Applicable': 'Non applicable',
    'Not Specified': 'Non spécifié',
    'To Be Determined': 'À déterminer',
    'Coming Soon': 'Bientôt disponible',
    'Under Construction': 'En construction',
    'Work in Progress': 'Travail en cours',
    'Beta': 'Beta',
    'Alpha': 'Alpha',
    'Experimental': 'Expérimental',
    'Deprecated': 'Déprécié',
    'Legacy': 'Hérité',
    'Obsolete': 'Obsolète',
    'Archived': 'Archivé',
    'Deleted': 'Supprimé',
    'Moved': 'Déplacé',
    'Renamed': 'Renommé',
    'Copied': 'Copié',
    'Cloned': 'Cloné',
    'Forked': 'Forké',
    'Branched': 'Branché',
    'Merged': 'Fusionné',
    'Committed': 'Commité',
    'Pushed': 'Poussé',
    'Pulled': 'Tiré',
    'Synced': 'Synchronisé',
    'Updated': 'Mis à jour',
    'Changed': 'Modifié',
    'Modified': 'Modifié',
    'Added': 'Ajouté',
    'Removed': 'Retiré',
    'Deleted': 'Supprimé',
    'Created': 'Créé',
    'Generated': 'Généré',
    'Calculated': 'Calculé',
    'Computed': 'Calculé',
    'Processed': 'Traité',
    'Executed': 'Exécuté',
    'Completed': 'Terminé',
    'Failed': 'Échoué',
    'Succeeded': 'Réussi',
    'Running': 'En cours',
    'Stopped': 'Arrêté',
    'Paused': 'En pause',
    'Resumed': 'Repris',
    'Started': 'Démarré',
    'Finished': 'Terminé',
    'Aborted': 'Abandonné',
    'Cancelled': 'Annulé',
    'Skipped': 'Ignoré',
    'Bypassed': 'Contourné',
    'Ignored': 'Ignoré',
    'Excluded': 'Exclu',
    'Included': 'Inclus',
    'Allowed': 'Autorisé',
    'Denied': 'Refusé',
    'Granted': 'Accordé',
    'Revoked': 'Révoqué',
    'Suspended': 'Suspendu',
    'Activated': 'Activé',
    'Deactivated': 'Désactivé',
    'Published': 'Publié',
    'Unpublished': 'Non publié',
    'Drafted': 'En brouillon',
    'Scheduled': 'Planifié',
    'Queued': 'En file d\'attente',
    'Processing': 'En traitement',
    'Pending': 'En attente',
    'Waiting': 'En attente',
    'Ready': 'Prêt',
    'Not Ready': 'Pas prêt',
    'Busy': 'Occupé',
    'Idle': 'Inactif',
    'Online': 'En ligne',
    'Offline': 'Hors ligne',
    'Connected': 'Connecté',
    'Disconnected': 'Déconnecté',
    'Available': 'Disponible',
    'Away': 'Absent',
    'Do Not Disturb': 'Ne pas déranger',
    'Invisible': 'Invisible',
}

def read_po_file(filepath):
    """Read the entire PO file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def write_po_file(filepath, content):
    """Write the updated PO file."""
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

def translate_string(msgid):
    """
    Translate an English string to French.
    Preserves placeholders, HTML tags, and special formatting.
    """
    # If empty, return empty
    if not msgid or msgid.strip() == '':
        return ''

    # Direct lookup first
    if msgid in TRANSLATIONS:
        return TRANSLATIONS[msgid]

    # For CRM terms
    for eng, fr in CRM_TERMS.items():
        if msgid == eng:
            return fr

    # Handle common patterns
    # This is a basic translation - for a production system,
    # you would use a proper translation API
    return None

def extract_entries(content):
    """Extract msgid/msgstr pairs from PO file content."""
    # Pattern to match msgid/msgstr pairs
    pattern = r'((?:^#.*\n)*)(msgid\s+"([^"]*)"\n(?:(?:"[^"]*"\n)*))msgstr\s+"([^"]*)"\n'
    matches = re.finditer(pattern, content, re.MULTILINE)

    entries = []
    for match in matches:
        comment = match.group(1)
        msgid_full = match.group(2)
        msgid = match.group(3)
        msgstr = match.group(4)

        # Extract full msgid value (including continuation lines)
        msgid_lines = re.findall(r'"([^"]*)"', msgid_full)
        msgid_value = ''.join(msgid_lines)

        entries.append({
            'comment': comment,
            'msgid_full': msgid_full,
            'msgid': msgid_value,
            'msgstr': msgstr,
            'full_match': match.group(0),
            'start': match.start(),
            'end': match.end()
        })

    return entries

def main():
    po_file = '/Users/jeremy/GitHub/crm/crm/locale/fr.po'

    print(f"Reading PO file: {po_file}")
    content = read_po_file(po_file)

    print("Extracting entries...")
    entries = extract_entries(content)

    print(f"Found {len(entries)} total entries")

    # Find entries with empty msgstr
    empty_entries = [e for e in entries if e['msgstr'] == '']
    print(f"Found {len(empty_entries)} empty translations")

    # Count translated
    translated_count = 0

    # For now, let's just identify what we can translate automatically
    translatable = []
    for entry in empty_entries:
        translation = translate_string(entry['msgid'])
        if translation:
            translatable.append((entry['msgid'], translation))
            translated_count += 1

    print(f"\nCan automatically translate {translated_count} entries")
    print(f"Remaining entries need manual translation: {len(empty_entries) - translated_count}")

    if translatable:
        print("\nSample automatic translations:")
        for eng, fr in translatable[:10]:
            print(f"  {eng} -> {fr}")

if __name__ == '__main__':
    main()
